# Generated by Django 4.0.4 on 2022-04-18 19:34

from django.db import migrations, models
import nutrition_blog.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_appuser_is_active_alter_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_photo/', validators=[nutrition_blog.accounts.validators.ValidateMaxSizeMB]),
        ),
    ]
